PPCR/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PPCR.Models;
using PagedList;
using PPCR.ViewModels;
using System.Data.Entity.Validation;

namespace PPCRentalProject.Controllers
{

    public class AdminController : Controller
    {
        DemoPPCRentalEntities entities = new DemoPPCRentalEntities();

        public ActionResult Admin_ControlPage(int? page)
        {
            var UserList = entities.USERs.ToList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            return View(UserList.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Admin_Decentralization(int id)
        {
            var UserInfo = entities.USERs.FirstOrDefault(x => x.ID == id);
            return View(UserInfo);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Admin_Decentralization(int id, USER user)
        {
            using (DemoPPCRentalEntities entities = new DemoPPCRentalEntities())
            {
                var EditedInfo = entities.USERs.FirstOrDefault(x => x.ID == id);
                EditedInfo.Email = user.Email;
                EditedInfo.Password = user.Password;
                EditedInfo.FullName = user.FullName;
                EditedInfo.Phone = user.Phone;
                EditedInfo.Address = user.Address;
                EditedInfo.Role = user.Role;
                EditedInfo.Status = user.Status;
                entities.Configuration.ValidateOnSaveEnabled = false;
                entities.SaveChanges();
            }
            return RedirectToAction("Admin_ControlPage");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Admin_ActivateAccount(int id, USER user)
        {
            using (DemoPPCRentalEntities entities = new DemoPPCRentalEntities())
            {
                var EditedInfo = entities.USERs.FirstOrDefault(x => x.ID == id);
                EditedInfo.Status = true;
                //entities.Configuration.ValidateOnSaveEnabled = false;
                entities.SaveChanges();
            }
            return RedirectToAction("Admin_ControlPage");
        }
    }
}

PPCR/Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PPCR.Models;
using PagedList;
using PPCR.ViewModels;

namespace PPCRentalProject.Controllers
{
    
    public class SaleController : Controller
    {
        DemoPPCRentalEntities entities = new DemoPPCRentalEntities();
        // GET: Sale
        public ActionResult Sale_ProjectsList(int? page)
        {
            var Properties = entities.PROPERTies.ToList();
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(Properties.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        public ActionResult Sale_EditProject(int id)
        {
            var ProjectDetails = entities.PROPERTies.FirstOrDefault(x => x.ID == id);
            ViewBag.Property_Type = entities.PROPERTY_TYPE.OrderByDescending(x => x.ID).ToList();
            ViewBag.StreetName = entities.STREETs.ToList();
            ViewBag.WardName = entities.WARDs.OrderByDescending(x => x.ID).ToList();
            ViewBag.DistrictName = entities.DISTRICTs.OrderByDescending(x => x.ID).ToList();
            return View(ProjectDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Sale_EditProject(int id, PROPERTY p)
        {
            var EditedInfo = entities.PROPERTies.FirstOrDefault(x => x.ID == id);
            EditedInfo.Avatar = p.Avatar;
            EditedInfo.Images = p.Images;
            EditedInfo.PropertyName = p.PropertyName;
            EditedInfo.PropertyType_ID = p.PropertyType_ID;
            EditedInfo.Area = p.Area;
            EditedInfo.BedRoom = p.BedRoom;
            EditedInfo.BathRoom = p.BathRoom;
            EditedInfo.PackingPlace = p.PackingPlace;
            EditedInfo.DISTRICT = p.DISTRICT;
            EditedInfo.WARD = p.WARD;
            EditedInfo.STREET = p.STREET;
            EditedInfo.Content = p.Content;
            EditedInfo.Status_ID = p.Status_ID;
            EditedInfo.Note = p.Note;
            entities.SaveChanges();
            return RedirectToAction("Sale_ProjectsList");
        }

        [HttpGet]
        public ActionResult Sale_ProjectTypeManage()
        {
            return View();
        }
    }
}

PPCR/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PPC Rental</title>

    <link href="~/Content/sb-admin-2.min.css" rel="stylesheet" />
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="~/Content/metisMenu.min.css" rel="stylesheet">
    <!-- DataTables CSS -->
    <link href="~/Content/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="~/Content/dataTables.responsive.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/sb-admin-2.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!--Navigation-->
    <nav class="navbar navbar-default navbar-static-top top-nav-collapse" style="margin-bottom: 0px">
        <div class="container">
            <div class="navbar-collapse collapse"></div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="font-size:29px;" href="@Url.Action("Admin_ControlPage","Admin")">PPC<span class="logo-dec">Rental</span></a>
            </div>
            <!-- /.navbar-header -->
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="#"><i class="fa fa-user fa-fw"></i> My Profile</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="@Url.Action("Logout", "Account")"><i class="fa fa-bolt" aria-hidden="true"></i> Log out</a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
                <!-- /.navbar-top-links -->
            </div>
        </div>

        <div class="navbar-default sidebar" style="margin-top: 0px" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    @if (ViewBag.Title == "Control Page" || ViewBag.Title == "Decentralization Page")
                    {
                        <li>
                            <a href="@Url.Action("Admin_ControlPage","Admin")" class="active"><i class="fa fa-user-circle" aria-hidden="true"></i> Users</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Charts</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action("Admin_ControlPage","Admin")"><i class="fa fa-user-circle" aria-hidden="true"></i> Users</a>
                        </li>
                        <li>
                            <a href="#" class="active"><i class="fa fa-bar-chart-o fa-fw"></i> Charts</a>
                        </li>
                    }
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>
    <div>
        @RenderBody()
    </div>

    <!-- jQuery -->
    <script src="~/Scripts/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Scripts/metisMenu.min.js"></script>
    <!-- DataTables JavaScript -->
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/dataTables.responsive.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Scripts/sb-admin-2.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PPCR/Views/Shared/_AgencyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PPC Rental</title>

    <link href="~/Content/sb-admin-2.min.css" rel="stylesheet" />
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="~/Content/metisMenu.min.css" rel="stylesheet">
    <!-- DataTables CSS -->
    <link href="~/Content/dataTables.bootstrap.css" rel="stylesheet">
    <!-- DataTables Responsive CSS -->
    <link href="~/Content/dataTables.responsive.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/sb-admin-2.min.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!--Navigation-->
    <nav class="navbar navbar-default navbar-static-top top-nav-collapse" style="margin-bottom: 0px">
        <div class="container">
            <div class="navbar-collapse collapse"></div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" style="font-size:29px;" href="@Url.Action("Index","Home")">PPC<span class="logo-dec">Rental</span></a>
            </div>
            <!-- /.navbar-header -->
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li>
                                <a href="@Url.Action("Index", "Home")"><i class="fa fa-user fa-fw"></i> Main Page</a>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <a href="@Url.Action("Logout", "Account")"><i class="fa fa-bolt" aria-hidden="true"></i> Log out</a>
                            </li>
                        </ul>
                        <!-- /.dropdown-user -->
                    </li>
                    <!-- /.dropdown -->
                </ul>
                <!-- /.navbar-top-links -->
            </div>
        </div>

        <div class="navbar-default sidebar" style="margin-top: 0px" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li class="sidebar-search">
                        <div class="input-group custom-search-form">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                        <!-- /input-group -->
                    </li>
                    @if (ViewBag.Title == "My Profile")
                    {
                        <li>
                            <a href="@Url.Action("Agency_AccountPage","Agency")/@Session["ID"]" class="active"><i class="fa fa-user-circle" aria-hidden="true"></i> My Profile</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Agency_ProjectsList","Agency")"><i class="fa fa-bar-chart-o fa-fw"></i> My Projects</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="@Url.Action("Agency_AccountPage","Agency")/@Session["ID"]"><i class="fa fa-user-circle" aria-hidden="true"></i> My Profile</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Agency_ProjectsList","Agency")" class="active"><i class="fa fa-bar-chart-o fa-fw"></i> My Projects</a>
                        </li>
                    }
                </ul>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>
    <div>
        @RenderBody()
    </div>

    <!-- jQuery -->
    <script src="~/Scripts/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Scripts/metisMenu.min.js"></script>
    <!-- DataTables JavaScript -->
    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/dataTables.bootstrap.min.js"></script>
    <script src="~/Scripts/dataTables.responsive.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Scripts/sb-admin-2.js"></script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PPCR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PPC Rental</title>

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:400,300|Raleway:300,400,900,700italic,700,300,600">
    <link rel="stylesheet" type="text/css" href="Content/jquery.bxslider.css">
    <link rel="stylesheet" type="text/css" href="Content/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="Content/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="Content/animate.css">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="loader"></div>
    <!--Navigation-->
    <nav class="navbar navbar-default navbar-fixed-top top-nav-collapse">
        <div class="container">
            <div class="navbar-collapse collapse"></div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="~/Home/Index">PPC<span class="logo-dec">Rental</span></a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right">
                    @if (ViewBag.Title == "Home Page")
                    {
                        <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="">@Html.ActionLink("About", "About", "Home")</li>
                        <li class=""><a href="#portfolio">Featured</a></li>
                        <li class=""><a href="#service">Services</a></li>
                        <li class=""><a href="#blog">Blog</a></li>
                        <li class=""><a href="#contact">Contact Us</a></li>
                    }
                    else if (ViewBag.Title == "About")
                    {
                        <li class="">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="active">@Html.ActionLink("About", "About", "Home")</li>
                        @*<li class=""><a style="pointer-events: none;cursor: default;">Featured</a></li>
                            <li class=""><a style="pointer-events: none;cursor: default;">Services</a></li>
                            <li class=""><a style="pointer-events: none;cursor: default;">Blog</a></li>
                            <li class=""><a style="pointer-events: none;cursor: default;">Contact Us</a></li>*@
                    }
                    else
                    {
                        <li class="">@Html.ActionLink("Home", "Index", "Home")</li>
                        <li class="">@Html.ActionLink("About", "About", "Home")</li>
                        @*<li class=""><a style="pointer-events: none;cursor: default;">Featured</a></li>
                            <li class=""><a style="pointer-events: none;cursor: default;">Services</a></li>
                            <li class=""><a style="pointer-events: none;cursor: default;">Blog</a></li>
                            <li class=""><a style="pointer-events: none;cursor: default;">Contact Us</a></li>*@
                    }
                    <li class=""><a href="#"> | </a></li>
                    @if (Convert.ToInt32(Session["Role"]) == 2)
                    {
                        <li class="">@Html.ActionLink("Projects List", "Sale_ProjectsList", "Sale")</li>
                    }
                    <li class="">@Html.Partial("_LoginPartial")</li>
                </ul>
            </div>
        </div>
    </nav>

    <div>
        @RenderBody()
        <!--Page's Footer-->
        <footer id="footer" style="background-color: rgba(73, 84, 105, 1.1)">
            <div class="container">
                <div class="row text-center">
                    <div style="position:static; letter-spacing:10px;">
                        <a href="#" target="_blank">@*Youtube*@<i class="fa fa-2x fa-youtube-square" aria-hidden="true"></i></a>
                        <a href="#" target="_blank">@*Facebook*@<i class="fa fa-2x fa-facebook-official" aria-hidden="true"></i></a>
                        <a href="#" target="_blank">@*Twitter*@<i class="fa fa-2x fa-twitter-square" aria-hidden="true"></i></a>
                        <a href="#" target="_blank">@*Linked In*@<i class="fa fa-2x fa-linkedin-square" aria-hidden="true"></i></a>
                        <a href="#" target="_blank">@*Instagram*@<i class="fa fa-2x fa-instagram" aria-hidden="true"></i></a>
                        <a href="#" target="_blank">@*Google Plus*@<i class="fa fa-2x fa-google-plus-square" aria-hidden="true"></i></a>
                        <a href="#" target="_blank">@*Pinterest*@<i class="fa fa-2x fa-pinterest-square" aria-hidden="true"></i></a>
                        <a href="#" target="_blank">@*Email*@<i class="fa fa-2x fa-envelope" aria-hidden="true"></i></a>
                    </div>
                    <div class="credits" style="position:static">
                        <span style="color:white"> Copyright © 2017 </span><a href="#">K21T2 - Dreamers</a>
                        <span style="color:white">. All rights reserved. <a class="sitemap" href="#">Sitemap</a> | Real Estate Website Design &amp; Internet Marketing by </span>
                        <a href="#">K21T2 - Dreamers</a>
                    </div>
                </div>
            </div>
        </footer>
        <!---->
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("upload", required: false)
</body>
</html>